MONGO_URI="mongodb+srv://Zyro:zyro9579@cluster0.i423szf.mongodb.net/?appName=Cluster0"

EXCHANGE_API="292d051ff9c049c8f1c4945d"

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "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"
client_id = "1013038889138-vccgita0jhbalmipnjssce7gfldd1f16.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"